version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Chicago
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      time: "07:30"
      timezone: America/Chicago
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    commit-message:
      prefix: build
