"""Generate offline JavaScript Public Suffix List bundles from the canonical data file.

Run from the repository root after refreshing ``data/public_suffix_list.dat``:

    python tools/generate_public_suffix_js.py

The web demo and Chromium extension are intentionally self-contained, so each
gets an identical generated bundle. The Python implementation continues to
read the canonical data file directly.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "public_suffix_list.dat"
DESTINATIONS = (
    ROOT / "web" / "public-suffix.js",
    ROOT / "browser-extension" / "chromium" / "public-suffix.js",
)


def load_rules(path: Path) -> tuple[list[str], list[str], list[str]]:
    normal: list[str] = []
    wildcard_bases: list[str] = []
    exceptions: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue
        rule = line.split()[0].lower()
        if rule.startswith("!"):
            exceptions.append(rule[1:])
        elif rule.startswith("*."):
            wildcard_bases.append(rule[2:])
        else:
            normal.append(rule)
    return normal, wildcard_bases, exceptions


def render(rules: tuple[list[str], list[str], list[str]]) -> str:
    normal, wildcard_bases, exceptions = rules

    def encoded(values: list[str]) -> str:
        return json.dumps(values, ensure_ascii=True, separators=(",", ":"))

    return f'''"use strict";

// Generated by tools/generate_public_suffix_js.py from
// data/public_suffix_list.dat. Do not edit this file by hand.
const PhishGuardPublicSuffix = (() => {{
  const NORMAL = new Set({encoded(normal)});
  const WILDCARD_BASES = new Set({encoded(wildcard_bases)});
  const EXCEPTIONS = new Set({encoded(exceptions)});

  function publicSuffixLength(labels) {{
    let best = null;
    for (let i = 0; i < labels.length; i += 1) {{
      const count = labels.length - i;
      const candidate = labels.slice(i).join(".");
      if (EXCEPTIONS.has(candidate)) return count - 1;
      if (NORMAL.has(candidate) && (best === null || count > best)) best = count;
      if (count >= 2) {{
        const remainder = labels.slice(i + 1).join(".");
        if (WILDCARD_BASES.has(remainder) && (best === null || count > best)) best = count;
      }}
    }}
    return best === null ? 1 : best;
  }}

  function registrableDomain(hostname) {{
    const normalized = String(hostname || "").replace(/^\\.+|\\.+$/g, "").toLowerCase();
    if (!normalized || !normalized.includes(".")) return normalized;
    const labels = normalized.split(".");
    const suffixLength = publicSuffixLength(labels);
    if (suffixLength >= labels.length) return normalized;
    return labels.slice(-(suffixLength + 1)).join(".");
  }}

  return {{ registrableDomain }};
}})();

if (typeof module !== "undefined" && module.exports) {{
  module.exports = PhishGuardPublicSuffix;
}}
'''


def generate() -> None:
    output = render(load_rules(SOURCE))
    for destination in DESTINATIONS:
        destination.write_text(output, encoding="utf-8", newline="\n")
        print(f"Wrote {destination.relative_to(ROOT)} ({len(output.encode('utf-8'))} bytes)")


def main() -> None:
    generate()


if __name__ == "__main__":
    main()
